name: Validate JSONs

on: [push, pull_request]

jobs:
  verify-INDEX-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./index.schema
          INPUT_JSONS: ./INDEX
  verify-Manifest-jsons:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "::set-env name=INPUT_JSON::$(ls -d ./*.json | xargs | tr -s '[:blank:]' ',')"
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./manifest.schema
          INPUT_JSONS: ${{env.INPUT_JSON}}
